#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagonetCore
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PAGONET_A")]
	public partial class profitDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertsaZona(saZona instance);
    partial void UpdatesaZona(saZona instance);
    partial void DeletesaZona(saZona instance);
    partial void InsertsaVendedor(saVendedor instance);
    partial void UpdatesaVendedor(saVendedor instance);
    partial void DeletesaVendedor(saVendedor instance);
    #endregion
		
		public profitDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PAGONET_AConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public profitDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public profitDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public profitDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public profitDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<saZona> saZona
		{
			get
			{
				return this.GetTable<saZona>();
			}
		}
		
		public System.Data.Linq.Table<saVendedor> saVendedor
		{
			get
			{
				return this.GetTable<saVendedor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.saZona")]
	public partial class saZona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _co_zon;
		
		private string _zon_des;
		
		private System.Nullable<int> _numcom;
		
		private System.Nullable<System.DateTime> _feccom;
		
		private System.Xml.Linq.XElement _dis_cen;
		
		private string _campo1;
		
		private string _campo2;
		
		private string _campo3;
		
		private string _campo4;
		
		private string _campo5;
		
		private string _campo6;
		
		private string _campo7;
		
		private string _campo8;
		
		private string _co_us_in;
		
		private string _co_sucu_in;
		
		private System.DateTime _fe_us_in;
		
		private string _co_us_mo;
		
		private string _co_sucu_mo;
		
		private System.DateTime _fe_us_mo;
		
		private System.Nullable<char> _revisado;
		
		private System.Nullable<char> _trasnfe;
		
		private System.Data.Linq.Binary _validador;
		
		private System.Guid _rowguid;
		
		private EntitySet<saVendedor> _saVendedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onco_zonChanging(string value);
    partial void Onco_zonChanged();
    partial void Onzon_desChanging(string value);
    partial void Onzon_desChanged();
    partial void OnnumcomChanging(System.Nullable<int> value);
    partial void OnnumcomChanged();
    partial void OnfeccomChanging(System.Nullable<System.DateTime> value);
    partial void OnfeccomChanged();
    partial void Ondis_cenChanging(System.Xml.Linq.XElement value);
    partial void Ondis_cenChanged();
    partial void Oncampo1Changing(string value);
    partial void Oncampo1Changed();
    partial void Oncampo2Changing(string value);
    partial void Oncampo2Changed();
    partial void Oncampo3Changing(string value);
    partial void Oncampo3Changed();
    partial void Oncampo4Changing(string value);
    partial void Oncampo4Changed();
    partial void Oncampo5Changing(string value);
    partial void Oncampo5Changed();
    partial void Oncampo6Changing(string value);
    partial void Oncampo6Changed();
    partial void Oncampo7Changing(string value);
    partial void Oncampo7Changed();
    partial void Oncampo8Changing(string value);
    partial void Oncampo8Changed();
    partial void Onco_us_inChanging(string value);
    partial void Onco_us_inChanged();
    partial void Onco_sucu_inChanging(string value);
    partial void Onco_sucu_inChanged();
    partial void Onfe_us_inChanging(System.DateTime value);
    partial void Onfe_us_inChanged();
    partial void Onco_us_moChanging(string value);
    partial void Onco_us_moChanged();
    partial void Onco_sucu_moChanging(string value);
    partial void Onco_sucu_moChanged();
    partial void Onfe_us_moChanging(System.DateTime value);
    partial void Onfe_us_moChanged();
    partial void OnrevisadoChanging(System.Nullable<char> value);
    partial void OnrevisadoChanged();
    partial void OntrasnfeChanging(System.Nullable<char> value);
    partial void OntrasnfeChanged();
    partial void OnvalidadorChanging(System.Data.Linq.Binary value);
    partial void OnvalidadorChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public saZona()
		{
			this._saVendedor = new EntitySet<saVendedor>(new Action<saVendedor>(this.attach_saVendedor), new Action<saVendedor>(this.detach_saVendedor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_zon", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string co_zon
		{
			get
			{
				return this._co_zon;
			}
			set
			{
				if ((this._co_zon != value))
				{
					this.Onco_zonChanging(value);
					this.SendPropertyChanging();
					this._co_zon = value;
					this.SendPropertyChanged("co_zon");
					this.Onco_zonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zon_des", DbType="VarChar(60) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string zon_des
		{
			get
			{
				return this._zon_des;
			}
			set
			{
				if ((this._zon_des != value))
				{
					this.Onzon_desChanging(value);
					this.SendPropertyChanging();
					this._zon_des = value;
					this.SendPropertyChanged("zon_des");
					this.Onzon_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numcom", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> numcom
		{
			get
			{
				return this._numcom;
			}
			set
			{
				if ((this._numcom != value))
				{
					this.OnnumcomChanging(value);
					this.SendPropertyChanging();
					this._numcom = value;
					this.SendPropertyChanged("numcom");
					this.OnnumcomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feccom", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> feccom
		{
			get
			{
				return this._feccom;
			}
			set
			{
				if ((this._feccom != value))
				{
					this.OnfeccomChanging(value);
					this.SendPropertyChanging();
					this._feccom = value;
					this.SendPropertyChanged("feccom");
					this.OnfeccomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_cen", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement dis_cen
		{
			get
			{
				return this._dis_cen;
			}
			set
			{
				if ((this._dis_cen != value))
				{
					this.Ondis_cenChanging(value);
					this.SendPropertyChanging();
					this._dis_cen = value;
					this.SendPropertyChanged("dis_cen");
					this.Ondis_cenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo1", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo1
		{
			get
			{
				return this._campo1;
			}
			set
			{
				if ((this._campo1 != value))
				{
					this.Oncampo1Changing(value);
					this.SendPropertyChanging();
					this._campo1 = value;
					this.SendPropertyChanged("campo1");
					this.Oncampo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo2", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo2
		{
			get
			{
				return this._campo2;
			}
			set
			{
				if ((this._campo2 != value))
				{
					this.Oncampo2Changing(value);
					this.SendPropertyChanging();
					this._campo2 = value;
					this.SendPropertyChanged("campo2");
					this.Oncampo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo3", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo3
		{
			get
			{
				return this._campo3;
			}
			set
			{
				if ((this._campo3 != value))
				{
					this.Oncampo3Changing(value);
					this.SendPropertyChanging();
					this._campo3 = value;
					this.SendPropertyChanged("campo3");
					this.Oncampo3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo4", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo4
		{
			get
			{
				return this._campo4;
			}
			set
			{
				if ((this._campo4 != value))
				{
					this.Oncampo4Changing(value);
					this.SendPropertyChanging();
					this._campo4 = value;
					this.SendPropertyChanged("campo4");
					this.Oncampo4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo5", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo5
		{
			get
			{
				return this._campo5;
			}
			set
			{
				if ((this._campo5 != value))
				{
					this.Oncampo5Changing(value);
					this.SendPropertyChanging();
					this._campo5 = value;
					this.SendPropertyChanged("campo5");
					this.Oncampo5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo6", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo6
		{
			get
			{
				return this._campo6;
			}
			set
			{
				if ((this._campo6 != value))
				{
					this.Oncampo6Changing(value);
					this.SendPropertyChanging();
					this._campo6 = value;
					this.SendPropertyChanged("campo6");
					this.Oncampo6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo7", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo7
		{
			get
			{
				return this._campo7;
			}
			set
			{
				if ((this._campo7 != value))
				{
					this.Oncampo7Changing(value);
					this.SendPropertyChanging();
					this._campo7 = value;
					this.SendPropertyChanged("campo7");
					this.Oncampo7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo8", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo8
		{
			get
			{
				return this._campo8;
			}
			set
			{
				if ((this._campo8 != value))
				{
					this.Oncampo8Changing(value);
					this.SendPropertyChanging();
					this._campo8 = value;
					this.SendPropertyChanged("campo8");
					this.Oncampo8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_us_in", DbType="Char(6) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string co_us_in
		{
			get
			{
				return this._co_us_in;
			}
			set
			{
				if ((this._co_us_in != value))
				{
					this.Onco_us_inChanging(value);
					this.SendPropertyChanging();
					this._co_us_in = value;
					this.SendPropertyChanged("co_us_in");
					this.Onco_us_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_sucu_in", DbType="Char(6)", UpdateCheck=UpdateCheck.Never)]
		public string co_sucu_in
		{
			get
			{
				return this._co_sucu_in;
			}
			set
			{
				if ((this._co_sucu_in != value))
				{
					this.Onco_sucu_inChanging(value);
					this.SendPropertyChanging();
					this._co_sucu_in = value;
					this.SendPropertyChanged("co_sucu_in");
					this.Onco_sucu_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fe_us_in", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime fe_us_in
		{
			get
			{
				return this._fe_us_in;
			}
			set
			{
				if ((this._fe_us_in != value))
				{
					this.Onfe_us_inChanging(value);
					this.SendPropertyChanging();
					this._fe_us_in = value;
					this.SendPropertyChanged("fe_us_in");
					this.Onfe_us_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_us_mo", DbType="Char(6) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string co_us_mo
		{
			get
			{
				return this._co_us_mo;
			}
			set
			{
				if ((this._co_us_mo != value))
				{
					this.Onco_us_moChanging(value);
					this.SendPropertyChanging();
					this._co_us_mo = value;
					this.SendPropertyChanged("co_us_mo");
					this.Onco_us_moChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_sucu_mo", DbType="Char(6)", UpdateCheck=UpdateCheck.Never)]
		public string co_sucu_mo
		{
			get
			{
				return this._co_sucu_mo;
			}
			set
			{
				if ((this._co_sucu_mo != value))
				{
					this.Onco_sucu_moChanging(value);
					this.SendPropertyChanging();
					this._co_sucu_mo = value;
					this.SendPropertyChanged("co_sucu_mo");
					this.Onco_sucu_moChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fe_us_mo", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime fe_us_mo
		{
			get
			{
				return this._fe_us_mo;
			}
			set
			{
				if ((this._fe_us_mo != value))
				{
					this.Onfe_us_moChanging(value);
					this.SendPropertyChanging();
					this._fe_us_mo = value;
					this.SendPropertyChanged("fe_us_mo");
					this.Onfe_us_moChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_revisado", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> revisado
		{
			get
			{
				return this._revisado;
			}
			set
			{
				if ((this._revisado != value))
				{
					this.OnrevisadoChanging(value);
					this.SendPropertyChanging();
					this._revisado = value;
					this.SendPropertyChanged("revisado");
					this.OnrevisadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trasnfe", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> trasnfe
		{
			get
			{
				return this._trasnfe;
			}
			set
			{
				if ((this._trasnfe != value))
				{
					this.OntrasnfeChanging(value);
					this.SendPropertyChanging();
					this._trasnfe = value;
					this.SendPropertyChanged("trasnfe");
					this.OntrasnfeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validador", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary validador
		{
			get
			{
				return this._validador;
			}
			set
			{
				if ((this._validador != value))
				{
					this.OnvalidadorChanging(value);
					this.SendPropertyChanging();
					this._validador = value;
					this.SendPropertyChanged("validador");
					this.OnvalidadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="saZona_saVendedor", Storage="_saVendedor", ThisKey="co_zon", OtherKey="co_zon")]
		public EntitySet<saVendedor> saVendedor
		{
			get
			{
				return this._saVendedor;
			}
			set
			{
				this._saVendedor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saVendedor(saVendedor entity)
		{
			this.SendPropertyChanging();
			entity.saZona = this;
		}
		
		private void detach_saVendedor(saVendedor entity)
		{
			this.SendPropertyChanging();
			entity.saZona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.saVendedor")]
	public partial class saVendedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _co_ven;
		
		private string _tipo;
		
		private string _ven_des;
		
		private System.Nullable<int> _numcom;
		
		private System.Nullable<System.DateTime> _feccom;
		
		private System.Xml.Linq.XElement _dis_cen;
		
		private string _cedula;
		
		private string _direc1;
		
		private string _direc2;
		
		private string _telefonos;
		
		private System.DateTime _fecha_reg;
		
		private bool _inactivo;
		
		private decimal _comision;
		
		private string _comentario;
		
		private bool _fun_cob;
		
		private bool _fun_ven;
		
		private System.Nullable<decimal> _comisionv;
		
		private string _login;
		
		private string _password;
		
		private string _email;
		
		private string _PSW_M;
		
		private string _campo1;
		
		private string _campo2;
		
		private string _campo3;
		
		private string _campo4;
		
		private string _campo5;
		
		private string _campo6;
		
		private string _campo7;
		
		private string _campo8;
		
		private string _co_us_in;
		
		private string _co_sucu_in;
		
		private System.DateTime _fe_us_in;
		
		private string _co_us_mo;
		
		private string _co_sucu_mo;
		
		private System.DateTime _fe_us_mo;
		
		private System.Nullable<char> _revisado;
		
		private System.Nullable<char> _trasnfe;
		
		private System.Data.Linq.Binary _validador;
		
		private System.Guid _rowguid;
		
		private string _co_zon;
		
		private EntityRef<saZona> _saZona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onco_venChanging(string value);
    partial void Onco_venChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void Onven_desChanging(string value);
    partial void Onven_desChanged();
    partial void OnnumcomChanging(System.Nullable<int> value);
    partial void OnnumcomChanged();
    partial void OnfeccomChanging(System.Nullable<System.DateTime> value);
    partial void OnfeccomChanged();
    partial void Ondis_cenChanging(System.Xml.Linq.XElement value);
    partial void Ondis_cenChanged();
    partial void OncedulaChanging(string value);
    partial void OncedulaChanged();
    partial void Ondirec1Changing(string value);
    partial void Ondirec1Changed();
    partial void Ondirec2Changing(string value);
    partial void Ondirec2Changed();
    partial void OntelefonosChanging(string value);
    partial void OntelefonosChanged();
    partial void Onfecha_regChanging(System.DateTime value);
    partial void Onfecha_regChanged();
    partial void OninactivoChanging(bool value);
    partial void OninactivoChanged();
    partial void OncomisionChanging(decimal value);
    partial void OncomisionChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void Onfun_cobChanging(bool value);
    partial void Onfun_cobChanged();
    partial void Onfun_venChanging(bool value);
    partial void Onfun_venChanged();
    partial void OncomisionvChanging(System.Nullable<decimal> value);
    partial void OncomisionvChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnPSW_MChanging(string value);
    partial void OnPSW_MChanged();
    partial void Oncampo1Changing(string value);
    partial void Oncampo1Changed();
    partial void Oncampo2Changing(string value);
    partial void Oncampo2Changed();
    partial void Oncampo3Changing(string value);
    partial void Oncampo3Changed();
    partial void Oncampo4Changing(string value);
    partial void Oncampo4Changed();
    partial void Oncampo5Changing(string value);
    partial void Oncampo5Changed();
    partial void Oncampo6Changing(string value);
    partial void Oncampo6Changed();
    partial void Oncampo7Changing(string value);
    partial void Oncampo7Changed();
    partial void Oncampo8Changing(string value);
    partial void Oncampo8Changed();
    partial void Onco_us_inChanging(string value);
    partial void Onco_us_inChanged();
    partial void Onco_sucu_inChanging(string value);
    partial void Onco_sucu_inChanged();
    partial void Onfe_us_inChanging(System.DateTime value);
    partial void Onfe_us_inChanged();
    partial void Onco_us_moChanging(string value);
    partial void Onco_us_moChanged();
    partial void Onco_sucu_moChanging(string value);
    partial void Onco_sucu_moChanged();
    partial void Onfe_us_moChanging(System.DateTime value);
    partial void Onfe_us_moChanged();
    partial void OnrevisadoChanging(System.Nullable<char> value);
    partial void OnrevisadoChanged();
    partial void OntrasnfeChanging(System.Nullable<char> value);
    partial void OntrasnfeChanged();
    partial void OnvalidadorChanging(System.Data.Linq.Binary value);
    partial void OnvalidadorChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    partial void Onco_zonChanging(string value);
    partial void Onco_zonChanged();
    #endregion
		
		public saVendedor()
		{
			this._saZona = default(EntityRef<saZona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_ven", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string co_ven
		{
			get
			{
				return this._co_ven;
			}
			set
			{
				if ((this._co_ven != value))
				{
					this.Onco_venChanging(value);
					this.SendPropertyChanging();
					this._co_ven = value;
					this.SendPropertyChanged("co_ven");
					this.Onco_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Char(4) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_des", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string ven_des
		{
			get
			{
				return this._ven_des;
			}
			set
			{
				if ((this._ven_des != value))
				{
					this.Onven_desChanging(value);
					this.SendPropertyChanging();
					this._ven_des = value;
					this.SendPropertyChanged("ven_des");
					this.Onven_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numcom", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> numcom
		{
			get
			{
				return this._numcom;
			}
			set
			{
				if ((this._numcom != value))
				{
					this.OnnumcomChanging(value);
					this.SendPropertyChanging();
					this._numcom = value;
					this.SendPropertyChanged("numcom");
					this.OnnumcomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feccom", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> feccom
		{
			get
			{
				return this._feccom;
			}
			set
			{
				if ((this._feccom != value))
				{
					this.OnfeccomChanging(value);
					this.SendPropertyChanging();
					this._feccom = value;
					this.SendPropertyChanged("feccom");
					this.OnfeccomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dis_cen", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement dis_cen
		{
			get
			{
				return this._dis_cen;
			}
			set
			{
				if ((this._dis_cen != value))
				{
					this.Ondis_cenChanging(value);
					this.SendPropertyChanging();
					this._dis_cen = value;
					this.SendPropertyChanged("dis_cen");
					this.Ondis_cenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Char(16)", UpdateCheck=UpdateCheck.Never)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direc1", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string direc1
		{
			get
			{
				return this._direc1;
			}
			set
			{
				if ((this._direc1 != value))
				{
					this.Ondirec1Changing(value);
					this.SendPropertyChanging();
					this._direc1 = value;
					this.SendPropertyChanged("direc1");
					this.Ondirec1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direc2", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string direc2
		{
			get
			{
				return this._direc2;
			}
			set
			{
				if ((this._direc2 != value))
				{
					this.Ondirec2Changing(value);
					this.SendPropertyChanging();
					this._direc2 = value;
					this.SendPropertyChanged("direc2");
					this.Ondirec2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonos", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string telefonos
		{
			get
			{
				return this._telefonos;
			}
			set
			{
				if ((this._telefonos != value))
				{
					this.OntelefonosChanging(value);
					this.SendPropertyChanging();
					this._telefonos = value;
					this.SendPropertyChanged("telefonos");
					this.OntelefonosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reg", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime fecha_reg
		{
			get
			{
				return this._fecha_reg;
			}
			set
			{
				if ((this._fecha_reg != value))
				{
					this.Onfecha_regChanging(value);
					this.SendPropertyChanging();
					this._fecha_reg = value;
					this.SendPropertyChanged("fecha_reg");
					this.Onfecha_regChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inactivo", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool inactivo
		{
			get
			{
				return this._inactivo;
			}
			set
			{
				if ((this._inactivo != value))
				{
					this.OninactivoChanging(value);
					this.SendPropertyChanging();
					this._inactivo = value;
					this.SendPropertyChanged("inactivo");
					this.OninactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comision", DbType="Decimal(18,2) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal comision
		{
			get
			{
				return this._comision;
			}
			set
			{
				if ((this._comision != value))
				{
					this.OncomisionChanging(value);
					this.SendPropertyChanging();
					this._comision = value;
					this.SendPropertyChanged("comision");
					this.OncomisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fun_cob", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool fun_cob
		{
			get
			{
				return this._fun_cob;
			}
			set
			{
				if ((this._fun_cob != value))
				{
					this.Onfun_cobChanging(value);
					this.SendPropertyChanging();
					this._fun_cob = value;
					this.SendPropertyChanged("fun_cob");
					this.Onfun_cobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fun_ven", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool fun_ven
		{
			get
			{
				return this._fun_ven;
			}
			set
			{
				if ((this._fun_ven != value))
				{
					this.Onfun_venChanging(value);
					this.SendPropertyChanging();
					this._fun_ven = value;
					this.SendPropertyChanged("fun_ven");
					this.Onfun_venChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comisionv", DbType="Decimal(18,2)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> comisionv
		{
			get
			{
				return this._comisionv;
			}
			set
			{
				if ((this._comisionv != value))
				{
					this.OncomisionvChanging(value);
					this.SendPropertyChanging();
					this._comisionv = value;
					this.SendPropertyChanged("comisionv");
					this.OncomisionvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PSW_M", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string PSW_M
		{
			get
			{
				return this._PSW_M;
			}
			set
			{
				if ((this._PSW_M != value))
				{
					this.OnPSW_MChanging(value);
					this.SendPropertyChanging();
					this._PSW_M = value;
					this.SendPropertyChanged("PSW_M");
					this.OnPSW_MChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo1", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo1
		{
			get
			{
				return this._campo1;
			}
			set
			{
				if ((this._campo1 != value))
				{
					this.Oncampo1Changing(value);
					this.SendPropertyChanging();
					this._campo1 = value;
					this.SendPropertyChanged("campo1");
					this.Oncampo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo2", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo2
		{
			get
			{
				return this._campo2;
			}
			set
			{
				if ((this._campo2 != value))
				{
					this.Oncampo2Changing(value);
					this.SendPropertyChanging();
					this._campo2 = value;
					this.SendPropertyChanged("campo2");
					this.Oncampo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo3", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo3
		{
			get
			{
				return this._campo3;
			}
			set
			{
				if ((this._campo3 != value))
				{
					this.Oncampo3Changing(value);
					this.SendPropertyChanging();
					this._campo3 = value;
					this.SendPropertyChanged("campo3");
					this.Oncampo3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo4", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo4
		{
			get
			{
				return this._campo4;
			}
			set
			{
				if ((this._campo4 != value))
				{
					this.Oncampo4Changing(value);
					this.SendPropertyChanging();
					this._campo4 = value;
					this.SendPropertyChanged("campo4");
					this.Oncampo4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo5", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo5
		{
			get
			{
				return this._campo5;
			}
			set
			{
				if ((this._campo5 != value))
				{
					this.Oncampo5Changing(value);
					this.SendPropertyChanging();
					this._campo5 = value;
					this.SendPropertyChanged("campo5");
					this.Oncampo5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo6", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo6
		{
			get
			{
				return this._campo6;
			}
			set
			{
				if ((this._campo6 != value))
				{
					this.Oncampo6Changing(value);
					this.SendPropertyChanging();
					this._campo6 = value;
					this.SendPropertyChanged("campo6");
					this.Oncampo6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo7", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo7
		{
			get
			{
				return this._campo7;
			}
			set
			{
				if ((this._campo7 != value))
				{
					this.Oncampo7Changing(value);
					this.SendPropertyChanging();
					this._campo7 = value;
					this.SendPropertyChanged("campo7");
					this.Oncampo7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campo8", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string campo8
		{
			get
			{
				return this._campo8;
			}
			set
			{
				if ((this._campo8 != value))
				{
					this.Oncampo8Changing(value);
					this.SendPropertyChanging();
					this._campo8 = value;
					this.SendPropertyChanged("campo8");
					this.Oncampo8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_us_in", DbType="Char(6) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string co_us_in
		{
			get
			{
				return this._co_us_in;
			}
			set
			{
				if ((this._co_us_in != value))
				{
					this.Onco_us_inChanging(value);
					this.SendPropertyChanging();
					this._co_us_in = value;
					this.SendPropertyChanged("co_us_in");
					this.Onco_us_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_sucu_in", DbType="Char(6)", UpdateCheck=UpdateCheck.Never)]
		public string co_sucu_in
		{
			get
			{
				return this._co_sucu_in;
			}
			set
			{
				if ((this._co_sucu_in != value))
				{
					this.Onco_sucu_inChanging(value);
					this.SendPropertyChanging();
					this._co_sucu_in = value;
					this.SendPropertyChanged("co_sucu_in");
					this.Onco_sucu_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fe_us_in", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime fe_us_in
		{
			get
			{
				return this._fe_us_in;
			}
			set
			{
				if ((this._fe_us_in != value))
				{
					this.Onfe_us_inChanging(value);
					this.SendPropertyChanging();
					this._fe_us_in = value;
					this.SendPropertyChanged("fe_us_in");
					this.Onfe_us_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_us_mo", DbType="Char(6) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string co_us_mo
		{
			get
			{
				return this._co_us_mo;
			}
			set
			{
				if ((this._co_us_mo != value))
				{
					this.Onco_us_moChanging(value);
					this.SendPropertyChanging();
					this._co_us_mo = value;
					this.SendPropertyChanged("co_us_mo");
					this.Onco_us_moChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_sucu_mo", DbType="Char(6)", UpdateCheck=UpdateCheck.Never)]
		public string co_sucu_mo
		{
			get
			{
				return this._co_sucu_mo;
			}
			set
			{
				if ((this._co_sucu_mo != value))
				{
					this.Onco_sucu_moChanging(value);
					this.SendPropertyChanging();
					this._co_sucu_mo = value;
					this.SendPropertyChanged("co_sucu_mo");
					this.Onco_sucu_moChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fe_us_mo", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime fe_us_mo
		{
			get
			{
				return this._fe_us_mo;
			}
			set
			{
				if ((this._fe_us_mo != value))
				{
					this.Onfe_us_moChanging(value);
					this.SendPropertyChanging();
					this._fe_us_mo = value;
					this.SendPropertyChanged("fe_us_mo");
					this.Onfe_us_moChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_revisado", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> revisado
		{
			get
			{
				return this._revisado;
			}
			set
			{
				if ((this._revisado != value))
				{
					this.OnrevisadoChanging(value);
					this.SendPropertyChanging();
					this._revisado = value;
					this.SendPropertyChanged("revisado");
					this.OnrevisadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trasnfe", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> trasnfe
		{
			get
			{
				return this._trasnfe;
			}
			set
			{
				if ((this._trasnfe != value))
				{
					this.OntrasnfeChanging(value);
					this.SendPropertyChanging();
					this._trasnfe = value;
					this.SendPropertyChanged("trasnfe");
					this.OntrasnfeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validador", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary validador
		{
			get
			{
				return this._validador;
			}
			set
			{
				if ((this._validador != value))
				{
					this.OnvalidadorChanging(value);
					this.SendPropertyChanging();
					this._validador = value;
					this.SendPropertyChanged("validador");
					this.OnvalidadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_zon", DbType="Char(6)", UpdateCheck=UpdateCheck.Never)]
		public string co_zon
		{
			get
			{
				return this._co_zon;
			}
			set
			{
				if ((this._co_zon != value))
				{
					if (this._saZona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onco_zonChanging(value);
					this.SendPropertyChanging();
					this._co_zon = value;
					this.SendPropertyChanged("co_zon");
					this.Onco_zonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="saZona_saVendedor", Storage="_saZona", ThisKey="co_zon", OtherKey="co_zon", IsForeignKey=true)]
		public saZona saZona
		{
			get
			{
				return this._saZona.Entity;
			}
			set
			{
				saZona previousValue = this._saZona.Entity;
				if (((previousValue != value) 
							|| (this._saZona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._saZona.Entity = null;
						previousValue.saVendedor.Remove(this);
					}
					this._saZona.Entity = value;
					if ((value != null))
					{
						value.saVendedor.Add(this);
						this._co_zon = value.co_zon;
					}
					else
					{
						this._co_zon = default(string);
					}
					this.SendPropertyChanged("saZona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
