//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagonetCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class saCuentaBancaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saCuentaBancaria()
        {
            this.saCobroTPReng = new HashSet<saCobroTPReng>();
            this.saMovimientoBanco = new HashSet<saMovimientoBanco>();
        }
    
        public string cod_cta { get; set; }
        public string co_ban { get; set; }
        public string co_mone { get; set; }
        public string num_cta { get; set; }
        public Nullable<int> numcom { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public string dis_cen { get; set; }
        public string telefonos { get; set; }
        public string sucursal { get; set; }
        public System.DateTime mes_ini { get; set; }
        public bool inactivo { get; set; }
        public bool usa_chra { get; set; }
        public string ejec_cu { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string tipo_cu { get; set; }
        public System.DateTime fecini { get; set; }
        public System.DateTime fec_chra { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<decimal> aux_imp01 { get; set; }
        public Nullable<decimal> aux_imp02 { get; set; }
    
        public virtual saBanco saBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saCobroTPReng> saCobroTPReng { get; set; }
        public virtual saMoneda saMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saMovimientoBanco> saMovimientoBanco { get; set; }
    }
}
