//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagonetCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class saMovimientoBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saMovimientoBanco()
        {
            this.saCobroTPReng = new HashSet<saCobroTPReng>();
            this.saDocumentoVenta = new HashSet<saDocumentoVenta>();
        }
    
        public string mov_num { get; set; }
        public string descrip { get; set; }
        public string cod_cta { get; set; }
        public string co_cta_ingr_egr { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal tasa { get; set; }
        public string tipo_op { get; set; }
        public string doc_num { get; set; }
        public decimal monto_d { get; set; }
        public decimal monto_h { get; set; }
        public decimal idb { get; set; }
        public bool saldo_ini { get; set; }
        public string origen { get; set; }
        public string cob_pag { get; set; }
        public string dep_num { get; set; }
        public bool conciliado { get; set; }
        public bool ori_dep { get; set; }
        public bool anulado { get; set; }
        public int dep_con { get; set; }
        public Nullable<System.DateTime> fec_con { get; set; }
        public string cod_ingben { get; set; }
        public System.DateTime fecha_che { get; set; }
        public Nullable<System.DateTime> feccom { get; set; }
        public Nullable<int> numcom { get; set; }
        public string dis_cen { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string trasnfe { get; set; }
        public string revisado { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> nro_transf_nomi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saCobroTPReng> saCobroTPReng { get; set; }
        public virtual saCuentaBancaria saCuentaBancaria { get; set; }
        public virtual saCuentaIngEgr saCuentaIngEgr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saDocumentoVenta> saDocumentoVenta { get; set; }
    }
}
